Call It Local/ClientApplicationMVC/Controllers/CompanyListingsController.cs
using ClientApplicationMVC.Models;
using Messages.DataTypes;
using Messages.DataTypes.Database.CompanyDirectory;
using Messages.ServiceBusRequest;
using Messages.ServiceBusRequest.CompanyDirectory.Responses;
using Messages.ServiceBusRequest.CompanyDirectory.Requests;


using System;
using System.Web.Mvc;
using System.Web.Routing;
using Messages.ServiceBusRequest.CompanyReviews;
using Messages.ServiceBusRequest.CompanyReviews.Requests;
using Messages.DataTypes.Database.CompanyReview;
using Messages.ServiceBusRequest.Weather.Requests;
using Messages.ServiceBusRequest.Weather.Response;

namespace ClientApplicationMVC.Controllers
{
    /// <summary>
    /// This class contains the functions responsible for handling requests routed to *Hostname*/CompanyListings/*
    /// </summary>
    public class CompanyListingsController : Controller
    {
        private static string companyNameeeee;
        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings
        /// </summary>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult Index()
        {
            if (Globals.isLoggedIn())
            {
                ViewBag.Companylist = null;
                return View("Index");
            }
            return RedirectToAction("Index", "Authentication");
        }

        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings/Search
        /// </summary>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult Search(string textCompanyName)
        {

            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if(connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            CompanySearchRequest request = new CompanySearchRequest(textCompanyName);

            CompanySearchResponse response = connection.searchCompanyByName(request);
            if (response.result == false)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ViewBag.Companylist = response.list;

            return View("Index");
        }

        public ActionResult Review(string companyReview, string companyStars)
        {
            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if (connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }
            DateTime now = DateTime.Now;
            AddCompanyReviewRequest request = new AddCompanyReviewRequest(new Review(companyNameeeee, companyReview, companyStars, now.ToString(), Globals.getUser()));
            ServiceBusResponse response = connection.addCompanyReview(request);
            
            //Can check if result is true here or just redirect to displaycompany and reload page
            
            return RedirectToAction("Index");
        }

        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings/DisplayCompany/*info*
        /// </summary>
        /// <param name="id">The name of the company whos info is to be displayed</param>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult DisplayCompany(string id)
        {
            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }
            if ("".Equals(id))
            {
                return View("Index");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if (connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ViewBag.CompanyName = id;
            companyNameeeee = id;
            string location = "";

            GetCompanyInfoRequest infoRequest = new GetCompanyInfoRequest(new CompanyInstance(id));
            GetCompanyInfoResponse infoResponse = connection.getCompanyInfo(infoRequest);
            ViewBag.CompanyInfo = infoResponse.companyInfo;
            location = infoResponse.companyInfo.locations[0];

            //CompanyReviewSearchRequest reviewRequest = new CompanyReviewSearchRequest(id);
           // CompanyReviewResponse reviewResponse = connection.searchCompanyReview(reviewRequest);
           // ViewBag.Reviewlist = reviewResponse.reviews;

            WeatherNeededRequest weatherRequest = new WeatherNeededRequest(location);
            WeatherNeededResponse weatherResponse = connection.getWeatherData(weatherRequest);
            if (!weatherResponse.result) {
                WeatherData wd = new WeatherData("not available", "not available", "not available", "not available", "not available", "not available");
                ViewBag.WeatherData = wd;
            }
            else {
                ViewBag.WeatherData = weatherResponse.weatherData;
            }
                
      
           
            return View("DisplayCompany");
        }
    }
}  

Call It Local/ClientApplicationMVC/Views/CompanyListings/DisplayCompany.cshtml
<link href="~/Content/ChatStyles.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="~/Scripts/CompanyListings/CompanyListingsFunctions.js"></script>

<h2 id="CompanyNameDisplay">@ViewBag.CompanyName</h2>
<section class="container">
    <div class="row">
        <div class="col-sm-6"

        <p>Email: @ViewBag.CompanyInfo.email</p>

        <p>Phone Number: @ViewBag.CompanyInfo.phoneNumber</p>

        <p>@ViewBag.CompanyName can be found at these locations:</p>
        @foreach(string location in ViewBag.CompanyInfo.locations)
        {
            <p style="padding-left:4em;">@location</p>
        }
        </div>
        <div class="col-sm-6" style="background-color: lightgray;">
            <h3>@ViewBag.CompanyInfo.locations[0]</h3>
            <p style="text-indent: 30px;">@ViewBag.WeatherData.weatherText</p>
            <figure class="col-sm-3">
                <img src="@Url.Content("~\\Icons\\" + @ViewBag.WeatherData.iconNum + "\\icon.png")">

            </figure>
            <p class="col-sm-3" style="font-weight: bold; font-size: 20px; font-family: Arial, Verdana, 'Times New Roman'">@ViewBag.WeatherData.temp @ViewBag.WeatherData.tempUnit</p>
            
        </div>                
    </div>
    <div class="row">
        <div class="col-sm-6">

        </div>
        <div class="col-sm-6" style="background-color: lightgray;">
            <p style="text-indent: 30px;">Feels like: @ViewBag.WeatherData.realTemp @ViewBag.WeatherData.realTempUnit</p>
        </div>
    </div>
</section>

<div style="height:100px">
    <h4>Start a conversation with @ViewBag.CompanyName</h4>
    <div style="width:400px; float:left">
        <textarea class="messagetextarea" id="textUserMessage" placeholder="Enter your message here." rows="3"></textarea>
    </div>
    <div style="float:left">
        <button class="sendbutton" id="SendMessageButton">Send</button>
    </div>
</div>

<div>
    <h4>@ViewBag.CompanyName Reviews:</h4>
    @if (ViewBag.Reviewlist != null)
    {
        if (ViewBag.Reviewlist.Count == 0)
        {
            <p>This company does not have any reviews. Be the first!</p>
        }
        else
        {
            <p style="font-size:larger">Results:</p> <br />
            foreach (var item in ViewBag.Reviewlist)
            {
                //@Html.ActionLink(item, "DisplayCompany/" + item, "CompanyListings")
                //TODO add this stuff when list structure is known
                <p>Username: @item.username</p>
                <p>Stars: @item.stars</p>
                <p>Review: @item.review</p>
                <p>Timestamp: @item.timestamp</p>
                <br />
            }
        }
    }
</div>
<div>
    <h4>Leave a review for @ViewBag.CompanyName</h4>
    @using (Html.BeginForm("Review", "CompanyListings"))
    {
        <div class="form-group">
            <label>Company Review</label>
            @Html.TextBox("companyReview")
        </div>
        <div class="form-group">
            <label>Stars</label>
            @Html.TextBox("companyStars")
        </div>
        <input type="submit" value="Review" />
    }
</div>
<br /><br />

Call It Local/ClientApplicationMVC/Views/CompanyListings/Index.cshtml
<!--
    This page will be used to search for and display Company names
-->
@{
    ViewBag.Title = "Index";
}

<h2>Search for companies by name</h2>

@using (Html.BeginForm("Search", "CompanyListings"))
{
    <p>@ViewBag.Message</p>
    <br />

    @Html.TextBox("textCompanyName")
    <input type="submit" value="Search" />
    <br /><br /><br />

    
}
@if (ViewBag.Companylist != null)
{
    if (ViewBag.Companylist.companyNames.Length == 0)
    {
        <p>Your search did not retrun any results. Please try again.</p>
    }
    else
    {
        <p style="font-size:larger">Results:</p> <br />
        foreach (string item in ViewBag.Companylist.companyNames)
        {
            @Html.ActionLink(item, "DisplayCompany/" + item, "CompanyListings")
            <br/>
        }
    }
}